FROM node:18-alpine3.17 AS builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile --production=false
RUN yarn build

FROM node:18-alpine3.17 AS runner
WORKDIR /app
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY package.json ./
COPY package-lock.json ./
RUN yarn install --frozen-lockfile --production=true
CMD ["yarn", "start"]
