services:
  app:
    tty: true
    networks:
      - chiloportfolio_app
    build:
      context: .
      dockerfile: Dockerfile.dev-local
    ports:
      - "3000:3000"
      - "5555:5555"
    # command: npm run dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    container_name: chiloportfolio_app

networks:
  chiloportfolio_app:
    driver: bridge
volumes:
  node_modules:
