version: "3.9"

services:
  chiloportfolio_app:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3001:3000"
    networks:
      - app_network
    container_name: chiloportfolio_app
    restart: "no"

networks:
  app_network:
    driver: bridge
    external: true
