version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    volumes:
      - ${SSL_CERTS_DIR}:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - chiloportfolio_app_network
    environment:
      # FORCE_RENEW: 'true'
      STAGE: production
      DOMAINS: "${ALLOWED_HOSTS} -> http://chiloportfolio_web:8081/"
    container_name: chiloportfolio_https_portal
    depends_on:
      - chiloportfolio_web

  web:
    image: nginx:1.23.1
    expose:
      - 8081
    networks:
      - chiloportfolio_app_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/workspace/static
      - ./50x.html:/usr/share/nginx/html/50x.html
    restart: always
    container_name: chiloportfolio_web
    depends_on:
      - chiloportfolio_app

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3001:3000"
    networks:
      - chiloportfolio_app_network
    container_name: chiloportfolio_app
    restart: "no"

networks:
  chiloportfolio_app_network:
    driver: bridge
