version: "3.9"

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3000:3000"
    networks:
      - app_network
    container_name: chiloportfolio
    restart: always
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '7'

networks:
  app_network:
    driver: bridge
    external: true
