version: "3.9"

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: sh -c "npm run dev"
    networks:
      - app_network
    container_name: chiloportfolio
    restart: always
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}

networks:
  app_network:
    driver: bridge
    external: true
