FROM node:16 AS builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile --production=false
RUN yarn build

FROM node:16 AS runner
WORKDIR /app
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY package.json ./
COPY package-lock.lock ./
RUN yarn install --frozen-lockfile --production=true
CMD ["yarn", "start"]

# EXPOSE 3000

# ENV PORT 3000
# ENV HOSTNAME localhost

CMD ["yarn", "start"]
